sudo: required
services:
  - docker

before_install:
  - docker build -t batnasan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true batnasan/docker-react npm run test -- --coverage

deploy:
  #edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-510871749779"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
